// src/lib/countries.ts
// Liste ISO 3166-1 alpha-2 des pays pour l'inscription obligatoire et le classement par pays

export interface CountryOption {
  code: string;
  name: string;
}

export const ISO_COUNTRIES: CountryOption[] = [
  { code: 'FR', name: 'France' },
  { code: 'BE', name: 'Belgique' },
  { code: 'CH', name: 'Suisse' },
  { code: 'CA', name: 'Canada' },
  { code: 'MA', name: 'Maroc' },
  { code: 'TN', name: 'Tunisie' },
  { code: 'DZ', name: 'Algérie' },
  { code: 'SN', name: 'Sénégal' },
  { code: 'CI', name: 'Côte d’Ivoire' },
  { code: 'CM', name: 'Cameroun' },
  { code: 'US', name: 'États-Unis' },
  { code: 'GB', name: 'Royaume-Uni' },
  { code: 'DE', name: 'Allemagne' },
  { code: 'ES', name: 'Espagne' },
  { code: 'IT', name: 'Italie' },
  { code: 'PT', name: 'Portugal' },
  { code: 'NL', name: 'Pays-Bas' },
  { code: 'LU', name: 'Luxembourg' },
  { code: 'MC', name: 'Monaco' },
  { code: 'NO', name: 'Norvège' },
  { code: 'SE', name: 'Suède' },
  { code: 'DK', name: 'Danemark' },
  { code: 'FI', name: 'Finlande' },
  { code: 'IS', name: 'Islande' },
  { code: 'PL', name: 'Pologne' },
  { code: 'CZ', name: 'Tchéquie' },
  { code: 'AT', name: 'Autriche' },
  { code: 'HU', name: 'Hongrie' },
  { code: 'RO', name: 'Roumanie' },
  { code: 'BG', name: 'Bulgarie' },
  { code: 'GR', name: 'Grèce' },
  { code: 'TR', name: 'Turquie' },
  { code: 'UA', name: 'Ukraine' },
  { code: 'AM', name: 'Arménie' },
  { code: 'GE', name: 'Géorgie' },
  { code: 'AZ', name: 'Azerbaïdjan' },
  { code: 'UZ', name: 'Ouzbékistan' },
  { code: 'KZ', name: 'Kazakhstan' },
  { code: 'IN', name: 'Inde' },
  { code: 'CN', name: 'Chine' },
  { code: 'JP', name: 'Japon' },
  { code: 'KR', name: 'Corée du Sud' },
  { code: 'VN', name: 'Viêt Nam' },
  { code: 'PH', name: 'Philippines' },
  { code: 'ID', name: 'Indonésie' },
  { code: 'SG', name: 'Singapour' },
  { code: 'AU', name: 'Australie' },
  { code: 'NZ', name: 'Nouvelle-Zélande' },
  { code: 'BR', name: 'Brésil' },
  { code: 'AR', name: 'Argentine' },
  { code: 'MX', name: 'Mexique' },
  { code: 'CO', name: 'Colombie' },
  { code: 'CL', name: 'Chili' },
  { code: 'PE', name: 'Pérou' },
  { code: 'CU', name: 'Cuba' },
  { code: 'EG', name: 'Égypte' },
  { code: 'ZA', name: 'Afrique du Sud' },
  { code: 'NG', name: 'Nigéria' },
  { code: 'KE', name: 'Kenya' },
  { code: 'MG', name: 'Madagascar' },
  { code: 'MU', name: 'Maurice' },
  { code: 'LB', name: 'Liban' },
  { code: 'AE', name: 'Émirats Arabes Unis' },
  { code: 'SA', name: 'Arabie Saoudite' },
  { code: 'QA', name: 'Qatar' },
  { code: 'IE', name: 'Irlande' },
  { code: 'HR', name: 'Croatie' },
  { code: 'RS', name: 'Serbie' },
  { code: 'SI', name: 'Slovénie' },
  { code: 'SK', name: 'Slovaquie' },
  { code: 'LT', name: 'Lituanie' },
  { code: 'LV', name: 'Lettonie' },
  { code: 'EE', name: 'Estonie' },
];

export function getCountryNameByCode(code: string): string {
  const found = ISO_COUNTRIES.find((c) => c.code.toUpperCase() === code.toUpperCase());
  return found ? found.name : code;
}
